//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1167.0 using the following command:
// XmlSchemaClassGenerator.Console -n cYo.Projects.ComicRack.Engine -i i -tns T:MetroninfoType=MetronInfo .\MetronInfo.xsd
namespace cYo.Projects.ComicRack.Engine
{


	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("metroninfoType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlRootAttribute("MetronInfo", Namespace = "")]
	public partial class MetronInfo
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<IdType> _ids;

		[System.Xml.Serialization.XmlArrayAttribute("IDS")]
		[System.Xml.Serialization.XmlArrayItemAttribute("ID")]
		public System.Collections.ObjectModel.Collection<IdType> Ids
		{
			get
			{
				return _ids;
			}
			private set
			{
				_ids = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Ids collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool IdsSpecified
		{
			get
			{
				return (this.Ids.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="MetronInfo" /> class.</para>
		/// </summary>
		public MetronInfo()
		{
			this._ids = new System.Collections.ObjectModel.Collection<IdType>();
			this._stories = new System.Collections.ObjectModel.Collection<ResourceType>();
			this._prices = new System.Collections.ObjectModel.Collection<PriceType>();
			this._genres = new System.Collections.ObjectModel.Collection<GenreType>();
			this._tags = new System.Collections.ObjectModel.Collection<ResourceType>();
			this._arcs = new System.Collections.ObjectModel.Collection<ArcType>();
			this._characters = new System.Collections.ObjectModel.Collection<ResourceType>();
			this._teams = new System.Collections.ObjectModel.Collection<ResourceType>();
			this._universes = new System.Collections.ObjectModel.Collection<UniverseType>();
			this._locations = new System.Collections.ObjectModel.Collection<ResourceType>();
			this._reprints = new System.Collections.ObjectModel.Collection<ResourceType>();
			this._urLs = new System.Collections.ObjectModel.Collection<UrlType>();
			this._credits = new System.Collections.ObjectModel.Collection<CreditType>();
		}

		[System.Xml.Serialization.XmlElementAttribute("Publisher")]
		public PublisherType Publisher { get; set; }

		[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
		[System.Xml.Serialization.XmlElementAttribute("Series")]
		public SeriesType Series { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("MangaVolume")]
		public string MangaVolume { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("CollectionTitle")]
		public string CollectionTitle { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("Number")]
		public string Number { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _stories;

		[System.Xml.Serialization.XmlArrayAttribute("Stories")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Story")]
		public System.Collections.ObjectModel.Collection<ResourceType> Stories
		{
			get
			{
				return _stories;
			}
			private set
			{
				_stories = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Stories collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool StoriesSpecified
		{
			get
			{
				return (this.Stories.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Summary")]
		public string Summary { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<PriceType> _prices;

		[System.Xml.Serialization.XmlArrayAttribute("Prices")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Price")]
		public System.Collections.ObjectModel.Collection<PriceType> Prices
		{
			get
			{
				return _prices;
			}
			private set
			{
				_prices = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Prices collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PricesSpecified
		{
			get
			{
				return (this.Prices.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("CoverDate", DataType = "date")]
		public System.DateTime CoverDate { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the CoverDate property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool CoverDateSpecified { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("StoreDate", DataType = "date")]
		public System.DateTime StoreDate { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the StoreDate property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool StoreDateSpecified { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private int _pageCount = 0;

		[System.ComponentModel.DefaultValueAttribute(0)]
		[System.Xml.Serialization.XmlElementAttribute("PageCount")]
		public int PageCount
		{
			get
			{
				return _pageCount;
			}
			set
			{
				_pageCount = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Notes")]
		public string Notes { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<GenreType> _genres;

		[System.Xml.Serialization.XmlArrayAttribute("Genres")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Genre")]
		public System.Collections.ObjectModel.Collection<GenreType> Genres
		{
			get
			{
				return _genres;
			}
			private set
			{
				_genres = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Genres collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool GenresSpecified
		{
			get
			{
				return (this.Genres.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _tags;

		[System.Xml.Serialization.XmlArrayAttribute("Tags")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Tag")]
		public System.Collections.ObjectModel.Collection<ResourceType> Tags
		{
			get
			{
				return _tags;
			}
			private set
			{
				_tags = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Tags collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool TagsSpecified
		{
			get
			{
				return (this.Tags.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ArcType> _arcs;

		[System.Xml.Serialization.XmlArrayAttribute("Arcs")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Arc")]
		public System.Collections.ObjectModel.Collection<ArcType> Arcs
		{
			get
			{
				return _arcs;
			}
			private set
			{
				_arcs = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Arcs collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ArcsSpecified
		{
			get
			{
				return (this.Arcs.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _characters;

		[System.Xml.Serialization.XmlArrayAttribute("Characters")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Character")]
		public System.Collections.ObjectModel.Collection<ResourceType> Characters
		{
			get
			{
				return _characters;
			}
			private set
			{
				_characters = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Characters collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool CharactersSpecified
		{
			get
			{
				return (this.Characters.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _teams;

		[System.Xml.Serialization.XmlArrayAttribute("Teams")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Team")]
		public System.Collections.ObjectModel.Collection<ResourceType> Teams
		{
			get
			{
				return _teams;
			}
			private set
			{
				_teams = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Teams collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool TeamsSpecified
		{
			get
			{
				return (this.Teams.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<UniverseType> _universes;

		[System.Xml.Serialization.XmlArrayAttribute("Universes")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Universe")]
		public System.Collections.ObjectModel.Collection<UniverseType> Universes
		{
			get
			{
				return _universes;
			}
			private set
			{
				_universes = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Universes collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool UniversesSpecified
		{
			get
			{
				return (this.Universes.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _locations;

		[System.Xml.Serialization.XmlArrayAttribute("Locations")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Location")]
		public System.Collections.ObjectModel.Collection<ResourceType> Locations
		{
			get
			{
				return _locations;
			}
			private set
			{
				_locations = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Locations collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool LocationsSpecified
		{
			get
			{
				return (this.Locations.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _reprints;

		[System.Xml.Serialization.XmlArrayAttribute("Reprints")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Reprint")]
		public System.Collections.ObjectModel.Collection<ResourceType> Reprints
		{
			get
			{
				return _reprints;
			}
			private set
			{
				_reprints = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Reprints collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ReprintsSpecified
		{
			get
			{
				return (this.Reprints.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("GTIN")]
		public GtinType Gtin { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private AgeRatingType _ageRating = cYo.Projects.ComicRack.Engine.AgeRatingType.Unknown;

		[System.ComponentModel.DefaultValueAttribute(cYo.Projects.ComicRack.Engine.AgeRatingType.Unknown)]
		[System.Xml.Serialization.XmlElementAttribute("AgeRating")]
		public AgeRatingType AgeRating
		{
			get
			{
				return _ageRating;
			}
			set
			{
				_ageRating = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<UrlType> _urLs;

		[System.Xml.Serialization.XmlArrayAttribute("URLs")]
		[System.Xml.Serialization.XmlArrayItemAttribute("URL")]
		public System.Collections.ObjectModel.Collection<UrlType> UrLs
		{
			get
			{
				return _urLs;
			}
			private set
			{
				_urLs = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the UrLs collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool UrLsSpecified
		{
			get
			{
				return (this.UrLs.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<CreditType> _credits;

		[System.Xml.Serialization.XmlArrayAttribute("Credits")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Credit")]
		public System.Collections.ObjectModel.Collection<CreditType> Credits
		{
			get
			{
				return _credits;
			}
			private set
			{
				_credits = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Credits collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool CreditsSpecified
		{
			get
			{
				return (this.Credits.Count != 0);
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("LastModified", DataType = "dateTime")]
		public System.DateTime LastModified { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the LastModified property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool LastModifiedSpecified { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("idsType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class IdsType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<IdType> _id;

		[System.Xml.Serialization.XmlElementAttribute("ID")]
		public System.Collections.ObjectModel.Collection<IdType> Id
		{
			get
			{
				return _id;
			}
			private set
			{
				_id = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Id collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool IdSpecified
		{
			get
			{
				return (this.Id.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="IdsType" /> class.</para>
		/// </summary>
		public IdsType()
		{
			this._id = new System.Collections.ObjectModel.Collection<IdType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("idType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class IdType
	{

		/// <summary>
		/// <para xml:lang="en">Gets or sets the text value.</para>
		/// </summary>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value { get; set; }

		[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
		[System.Xml.Serialization.XmlAttributeAttribute("source")]
		public InformationSource Source { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("primary")]
		public bool Primary { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the Primary property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PrimarySpecified { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("informationSource", Namespace = "")]
	public enum InformationSource
	{

		AniList,

		[System.Xml.Serialization.XmlEnumAttribute("Comic Vine")]
		ComicVine,

		[System.Xml.Serialization.XmlEnumAttribute("Grand Comics Database")]
		GrandComicsDatabase,

		Kitsu,

		MangaDex,

		MangaUpdates,

		Marvel,

		Metron,

		MyAnimeList,

		[System.Xml.Serialization.XmlEnumAttribute("League of Comic Geeks")]
		LeagueOfComicGeeks,
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("publisherType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class PublisherType
	{

		[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
		[System.Xml.Serialization.XmlElementAttribute("Name")]
		public string Name { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("Imprint")]
		public ResourceType Imprint { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("id")]
		public string Id { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("resourceType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ResourceType
	{

		/// <summary>
		/// <para xml:lang="en">Gets or sets the text value.</para>
		/// </summary>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("id")]
		public string Id { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("seriesType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class SeriesType
	{

		[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
		[System.Xml.Serialization.XmlElementAttribute("Name")]
		public string Name { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("SortName")]
		public string SortName { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("Volume")]
		public int Volume { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the Volume property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool VolumeSpecified { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("Format")]
		public FormatType Format { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the Format property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool FormatSpecified { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("StartYear")]
		public string StartYear { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("IssueCount")]
		public int IssueCount { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the IssueCount property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool IssueCountSpecified { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("VolumeCount")]
		public int VolumeCount { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the VolumeCount property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool VolumeCountSpecified { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<NameType> _alternativeNames;

		[System.Xml.Serialization.XmlArrayAttribute("AlternativeNames")]
		[System.Xml.Serialization.XmlArrayItemAttribute("AlternativeName")]
		public System.Collections.ObjectModel.Collection<NameType> AlternativeNames
		{
			get
			{
				return _alternativeNames;
			}
			private set
			{
				_alternativeNames = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the AlternativeNames collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool AlternativeNamesSpecified
		{
			get
			{
				return (this.AlternativeNames.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="SeriesType" /> class.</para>
		/// </summary>
		public SeriesType()
		{
			this._alternativeNames = new System.Collections.ObjectModel.Collection<NameType>();
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private string _lang = "en";

		/// <summary>
		/// <para xml:lang="en">Pattern: [a-z][a-z].</para>
		/// </summary>
		[System.ComponentModel.DefaultValueAttribute("en")]
		[System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-z][a-z]")]
		[System.Xml.Serialization.XmlAttributeAttribute("lang")]
		public string Lang
		{
			get
			{
				return _lang;
			}
			set
			{
				_lang = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute("id")]
		public string Id { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("formatType", Namespace = "")]
	public enum FormatType
	{

		Annual,

		[System.Xml.Serialization.XmlEnumAttribute("Digital Chapter")]
		DigitalChapter,

		[System.Xml.Serialization.XmlEnumAttribute("Graphic Novel")]
		GraphicNovel,

		Hardcover,

		[System.Xml.Serialization.XmlEnumAttribute("Limited Series")]
		LimitedSeries,

		Omnibus,

		[System.Xml.Serialization.XmlEnumAttribute("One-Shot")]
		OneShot,

		[System.Xml.Serialization.XmlEnumAttribute("Single Issue")]
		SingleIssue,

		[System.Xml.Serialization.XmlEnumAttribute("Trade Paperback")]
		TradePaperback,
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("alternativeNameType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class AlternativeNameType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<NameType> _alternativeName;

		[System.Xml.Serialization.XmlElementAttribute("AlternativeName")]
		public System.Collections.ObjectModel.Collection<NameType> AlternativeName
		{
			get
			{
				return _alternativeName;
			}
			private set
			{
				_alternativeName = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the AlternativeName collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool AlternativeNameSpecified
		{
			get
			{
				return (this.AlternativeName.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="AlternativeNameType" /> class.</para>
		/// </summary>
		public AlternativeNameType()
		{
			this._alternativeName = new System.Collections.ObjectModel.Collection<NameType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("nameType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class NameType
	{

		/// <summary>
		/// <para xml:lang="en">Gets or sets the text value.</para>
		/// </summary>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("id")]
		public string Id { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private string _lang = "en";

		/// <summary>
		/// <para xml:lang="en">Pattern: [a-z][a-z].</para>
		/// </summary>
		[System.ComponentModel.DefaultValueAttribute("en")]
		[System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-z][a-z]")]
		[System.Xml.Serialization.XmlAttributeAttribute("lang")]
		public string Lang
		{
			get
			{
				return _lang;
			}
			set
			{
				_lang = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("storyType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class StoryType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _story;

		[System.Xml.Serialization.XmlElementAttribute("Story")]
		public System.Collections.ObjectModel.Collection<ResourceType> Story
		{
			get
			{
				return _story;
			}
			private set
			{
				_story = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Story collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool StorySpecified
		{
			get
			{
				return (this.Story.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="StoryType" /> class.</para>
		/// </summary>
		public StoryType()
		{
			this._story = new System.Collections.ObjectModel.Collection<ResourceType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("pricesType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class PricesType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<PriceType> _price;

		[System.Xml.Serialization.XmlElementAttribute("Price")]
		public System.Collections.ObjectModel.Collection<PriceType> Price
		{
			get
			{
				return _price;
			}
			private set
			{
				_price = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Price collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PriceSpecified
		{
			get
			{
				return (this.Price.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="PricesType" /> class.</para>
		/// </summary>
		public PricesType()
		{
			this._price = new System.Collections.ObjectModel.Collection<PriceType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("priceType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class PriceType
	{

		/// <summary>
		/// <para xml:lang="en">Gets or sets the text value.</para>
		/// </summary>
		[System.Xml.Serialization.XmlTextAttribute()]
		public decimal Value { get; set; }

		/// <summary>
		/// <para xml:lang="en">Pattern: [A-Z][A-Z].</para>
		/// </summary>
		[System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z][A-Z]")]
		[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
		[System.Xml.Serialization.XmlAttributeAttribute("country")]
		public string Country { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("genresType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GenresType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<GenreType> _genre;

		[System.Xml.Serialization.XmlElementAttribute("Genre")]
		public System.Collections.ObjectModel.Collection<GenreType> Genre
		{
			get
			{
				return _genre;
			}
			private set
			{
				_genre = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Genre collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool GenreSpecified
		{
			get
			{
				return (this.Genre.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="GenresType" /> class.</para>
		/// </summary>
		public GenresType()
		{
			this._genre = new System.Collections.ObjectModel.Collection<GenreType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("genreType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GenreType
	{

		/// <summary>
		/// <para xml:lang="en">Gets or sets the text value.</para>
		/// </summary>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("id")]
		public string Id { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("tagsType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class TagsType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _tag;

		[System.Xml.Serialization.XmlElementAttribute("Tag")]
		public System.Collections.ObjectModel.Collection<ResourceType> Tag
		{
			get
			{
				return _tag;
			}
			private set
			{
				_tag = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Tag collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool TagSpecified
		{
			get
			{
				return (this.Tag.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="TagsType" /> class.</para>
		/// </summary>
		public TagsType()
		{
			this._tag = new System.Collections.ObjectModel.Collection<ResourceType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("arcsType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ArcsType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ArcType> _arc;

		[System.Xml.Serialization.XmlElementAttribute("Arc")]
		public System.Collections.ObjectModel.Collection<ArcType> Arc
		{
			get
			{
				return _arc;
			}
			private set
			{
				_arc = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Arc collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ArcSpecified
		{
			get
			{
				return (this.Arc.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="ArcsType" /> class.</para>
		/// </summary>
		public ArcsType()
		{
			this._arc = new System.Collections.ObjectModel.Collection<ArcType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("arcType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ArcType
	{

		[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
		[System.Xml.Serialization.XmlElementAttribute("Name")]
		public string Name { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("Number")]
		public int Number { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the Number property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool NumberSpecified { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("id")]
		public string Id { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("charactersType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class CharactersType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _character;

		[System.Xml.Serialization.XmlElementAttribute("Character")]
		public System.Collections.ObjectModel.Collection<ResourceType> Character
		{
			get
			{
				return _character;
			}
			private set
			{
				_character = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Character collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool CharacterSpecified
		{
			get
			{
				return (this.Character.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="CharactersType" /> class.</para>
		/// </summary>
		public CharactersType()
		{
			this._character = new System.Collections.ObjectModel.Collection<ResourceType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("teamsType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class TeamsType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _team;

		[System.Xml.Serialization.XmlElementAttribute("Team")]
		public System.Collections.ObjectModel.Collection<ResourceType> Team
		{
			get
			{
				return _team;
			}
			private set
			{
				_team = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Team collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool TeamSpecified
		{
			get
			{
				return (this.Team.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="TeamsType" /> class.</para>
		/// </summary>
		public TeamsType()
		{
			this._team = new System.Collections.ObjectModel.Collection<ResourceType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("universesType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class UniversesType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<UniverseType> _universe;

		[System.Xml.Serialization.XmlElementAttribute("Universe")]
		public System.Collections.ObjectModel.Collection<UniverseType> Universe
		{
			get
			{
				return _universe;
			}
			private set
			{
				_universe = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Universe collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool UniverseSpecified
		{
			get
			{
				return (this.Universe.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="UniversesType" /> class.</para>
		/// </summary>
		public UniversesType()
		{
			this._universe = new System.Collections.ObjectModel.Collection<UniverseType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("universeType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class UniverseType
	{

		[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
		[System.Xml.Serialization.XmlElementAttribute("Name")]
		public string Name { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("Designation")]
		public string Designation { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("id")]
		public string Id { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("locationsType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class LocationsType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _location;

		[System.Xml.Serialization.XmlElementAttribute("Location")]
		public System.Collections.ObjectModel.Collection<ResourceType> Location
		{
			get
			{
				return _location;
			}
			private set
			{
				_location = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Location collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool LocationSpecified
		{
			get
			{
				return (this.Location.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="LocationsType" /> class.</para>
		/// </summary>
		public LocationsType()
		{
			this._location = new System.Collections.ObjectModel.Collection<ResourceType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("reprintsType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class ReprintsType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<ResourceType> _reprint;

		[System.Xml.Serialization.XmlElementAttribute("Reprint")]
		public System.Collections.ObjectModel.Collection<ResourceType> Reprint
		{
			get
			{
				return _reprint;
			}
			private set
			{
				_reprint = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Reprint collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ReprintSpecified
		{
			get
			{
				return (this.Reprint.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="ReprintsType" /> class.</para>
		/// </summary>
		public ReprintsType()
		{
			this._reprint = new System.Collections.ObjectModel.Collection<ResourceType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("gtinType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class GtinType
	{

		[System.Xml.Serialization.XmlElementAttribute("ISBN")]
		public object Isbn { get; set; }

		[System.Xml.Serialization.XmlElementAttribute("UPC")]
		public object Upc { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("ageRatingType", Namespace = "")]
	public enum AgeRatingType
	{

		Unknown,

		Everyone,

		Teen,

		[System.Xml.Serialization.XmlEnumAttribute("Teen Plus")]
		TeenPlus,

		Mature,

		Explicit,

		Adult,
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("urlsType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class UrlsType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<UrlType> _url;

		[System.Xml.Serialization.XmlElementAttribute("URL")]
		public System.Collections.ObjectModel.Collection<UrlType> Url
		{
			get
			{
				return _url;
			}
			private set
			{
				_url = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Url collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool UrlSpecified
		{
			get
			{
				return (this.Url.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="UrlsType" /> class.</para>
		/// </summary>
		public UrlsType()
		{
			this._url = new System.Collections.ObjectModel.Collection<UrlType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("urlType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class UrlType
	{

		/// <summary>
		/// <para xml:lang="en">Gets or sets the text value.</para>
		/// </summary>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("primary")]
		public bool Primary { get; set; }

		/// <summary>
		/// <para xml:lang="en">Gets or sets a value indicating whether the Primary property is specified.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool PrimarySpecified { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("creditsType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class CreditsType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<CreditType> _credit;

		[System.Xml.Serialization.XmlElementAttribute("Credit")]
		public System.Collections.ObjectModel.Collection<CreditType> Credit
		{
			get
			{
				return _credit;
			}
			private set
			{
				_credit = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Credit collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool CreditSpecified
		{
			get
			{
				return (this.Credit.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="CreditsType" /> class.</para>
		/// </summary>
		public CreditsType()
		{
			this._credit = new System.Collections.ObjectModel.Collection<CreditType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("creditType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class CreditType
	{

		[System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
		[System.Xml.Serialization.XmlElementAttribute("Creator")]
		public ResourceType Creator { get; set; }

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<RoleType> _roles;

		[System.Xml.Serialization.XmlArrayAttribute("Roles")]
		[System.Xml.Serialization.XmlArrayItemAttribute("Role")]
		public System.Collections.ObjectModel.Collection<RoleType> Roles
		{
			get
			{
				return _roles;
			}
			private set
			{
				_roles = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Roles collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool RolesSpecified
		{
			get
			{
				return (this.Roles.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="CreditType" /> class.</para>
		/// </summary>
		public CreditType()
		{
			this._roles = new System.Collections.ObjectModel.Collection<RoleType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("rolesType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class RolesType
	{

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		private System.Collections.ObjectModel.Collection<RoleType> _role;

		[System.Xml.Serialization.XmlElementAttribute("Role")]
		public System.Collections.ObjectModel.Collection<RoleType> Role
		{
			get
			{
				return _role;
			}
			private set
			{
				_role = value;
			}
		}

		/// <summary>
		/// <para xml:lang="en">Gets a value indicating whether the Role collection is empty.</para>
		/// </summary>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool RoleSpecified
		{
			get
			{
				return (this.Role.Count != 0);
			}
		}

		/// <summary>
		/// <para xml:lang="en">Initializes a new instance of the <see cref="RolesType" /> class.</para>
		/// </summary>
		public RolesType()
		{
			this._role = new System.Collections.ObjectModel.Collection<RoleType>();
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("roleType", Namespace = "")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class RoleType
	{

		/// <summary>
		/// <para xml:lang="en">Gets or sets the text value.</para>
		/// </summary>
		[System.Xml.Serialization.XmlTextAttribute()]
		public RoleValues Value { get; set; }

		[System.Xml.Serialization.XmlAttributeAttribute("id")]
		public string Id { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1167.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute("roleValues", Namespace = "")]
	public enum RoleValues
	{

		Writer,

		Script,

		Story,

		Plot,

		Interviewer,

		Artist,

		Penciller,

		Breakdowns,

		Illustrator,

		Layouts,

		Inker,

		Embellisher,

		Finishes,

		[System.Xml.Serialization.XmlEnumAttribute("Ink Assists")]
		InkAssists,

		Colorist,

		[System.Xml.Serialization.XmlEnumAttribute("Color Separations")]
		ColorSeparations,

		[System.Xml.Serialization.XmlEnumAttribute("Color Assists")]
		ColorAssists,

		[System.Xml.Serialization.XmlEnumAttribute("Color Flats")]
		ColorFlats,

		[System.Xml.Serialization.XmlEnumAttribute("Digital Art Technician")]
		DigitalArtTechnician,

		[System.Xml.Serialization.XmlEnumAttribute("Gray Tone")]
		GrayTone,

		Letterer,

		Cover,

		Editor,

		[System.Xml.Serialization.XmlEnumAttribute("Consulting Editor")]
		ConsultingEditor,

		[System.Xml.Serialization.XmlEnumAttribute("Assistant Editor")]
		AssistantEditor,

		[System.Xml.Serialization.XmlEnumAttribute("Associate Editor")]
		AssociateEditor,

		[System.Xml.Serialization.XmlEnumAttribute("Group Editor")]
		GroupEditor,

		[System.Xml.Serialization.XmlEnumAttribute("Senior Editor")]
		SeniorEditor,

		[System.Xml.Serialization.XmlEnumAttribute("Managing Editor")]
		ManagingEditor,

		[System.Xml.Serialization.XmlEnumAttribute("Collection Editor")]
		CollectionEditor,

		Production,

		Designer,

		[System.Xml.Serialization.XmlEnumAttribute("Logo Design")]
		LogoDesign,

		Translator,

		[System.Xml.Serialization.XmlEnumAttribute("Supervising Editor")]
		SupervisingEditor,

		[System.Xml.Serialization.XmlEnumAttribute("Executive Editor")]
		ExecutiveEditor,

		[System.Xml.Serialization.XmlEnumAttribute("Editor In Chief")]
		EditorInChief,

		President,

		Publisher,

		[System.Xml.Serialization.XmlEnumAttribute("Chief Creative Officer")]
		ChiefCreativeOfficer,

		[System.Xml.Serialization.XmlEnumAttribute("Executive Producer")]
		ExecutiveProducer,

		Other,
	}
}
